Repository eduardconstantin/Comic-book-button-anim, pull requests merged in 2022-10, with the labels that each got.

#11 Issue Of Readme Solved
  Contributing-Guidlines.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted

#5 Cursor style- Grab
  src/index.css
Labels: enhancement, hacktoberfest-accepted

#14 Added scale up on focus
  package-lock.json
  src/App.js
  src/components/ComicButton/ComicButton.anim.jsx
  src/components/ComicButton/ComicButton.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#15 did some design improvements
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#20 Create pull request template
  .github/pull_request_template.md
Labels: documentation, hacktoberfest-accepted

#22 Code of Conduct
  Code_of_Conduct.md
Labels: documentation, hacktoberfest-accepted

#21 Added custom cursor
  package-lock.json
  src/components/ComicButton/ComicButton.module.css
  src/components/ComicButton/img/arrow.png
  src/components/ComicButton/img/clicked.png
  src/components/ComicButton/img/pointer.png
  src/index.css
Labels: enhancement, hacktoberfest-accepted

#33 [Feature] Create npm package
  .all-contributorsrc
  NPM_PACKAGE/comic-book-button-1/.npmrc
  NPM_PACKAGE/comic-book-button-1/.storybook/main.js
  NPM_PACKAGE/comic-book-button-1/.storybook/preview.js
  NPM_PACKAGE/comic-book-button-1/dist/ComicButton.anim.d.ts
  NPM_PACKAGE/comic-book-button-1/dist/ComicButton.d.ts
  NPM_PACKAGE/comic-book-button-1/dist/index.d.ts
  NPM_PACKAGE/comic-book-button-1/dist/index.js
  NPM_PACKAGE/comic-book-button-1/package-lock.json
  NPM_PACKAGE/comic-book-button-1/package.json
  NPM_PACKAGE/comic-book-button-1/rollup.config.js
  NPM_PACKAGE/comic-book-button-1/stories/ComicButton.anim.tsx
  NPM_PACKAGE/comic-book-button-1/stories/ComicButton.module.css
  NPM_PACKAGE/comic-book-button-1/stories/ComicButton.tsx
  NPM_PACKAGE/comic-book-button-1/stories/custom.d.ts
  NPM_PACKAGE/comic-book-button-1/stories/img/arrow.png
  NPM_PACKAGE/comic-book-button-1/stories/img/click.png
  NPM_PACKAGE/comic-book-button-1/stories/img/clicked.png
  NPM_PACKAGE/comic-book-button-1/stories/img/dots.png
  NPM_PACKAGE/comic-book-button-1/stories/img/pointer.png
  NPM_PACKAGE/comic-book-button-1/stories/index.ts
  NPM_PACKAGE/comic-book-button-1/tsconfig.json
  README.md
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest-accepted

#32 Feature : Add counter [fixes #27]
  src/App.tsx
  src/components/ComicButton/ComicButton.tsx
  src/components/Counter/Counter.module.css
  src/components/Counter/Counter.tsx
  src/index.css
Labels: enhancement, hacktoberfest-accepted

#36 added github star button
  public/index.html
Labels: good first issue, hacktoberfest-accepted

#39 add btnClassName to ComicButton
  src/components/ComicButton/ComicButton.tsx
Labels: enhancement, hacktoberfest-accepted

#38 Add ComicButton styled GitHub stargazer counter
  public/github.png
  public/index.html
  src/App.tsx
  src/components/GithubStargazers/GithubStargazers.module.css
  src/components/GithubStargazers/GithubStargazers.tsx
  src/index.css
Labels: enhancement, hacktoberfest-accepted

#41 fix icon loading
  src/components/GithubStargazers/GithubStargazers.tsx
Labels: bug
